[package]
name = "mesh-protocol"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
log = "0.4.26"
tokio = { version = "1.49.0", features = ["full"] }
android_logger = "0.13.3"
ndk-context = "0.1.1"
btleplug = "0.11"
